CodeSystem: LocationTypeCS
Id: location-type-cs
Title: "Organisaation tilatyypit"
Description: "Organisaation sisäiseen käyttöön tarkoitettu koodisto eri tilatyypeille, joita käytetään Location-resurssissa."
* ^url = "http://example.org/fhir/CodeSystem/location-type-cs"
* ^status = #active
* ^content = #complete

* #211 "Toimistotila"
* #2112 "Toimistotila, erikoisvarustus"
* #214 "Kokoustila"
* #215 "Monitoimityötila"
* #22 "Liiketila"
* #31 "Opetustila tai luentosali"
* #3249 "Muu opetus- tai terapiatila"
* #362 "Laboratorio"
* #3651 "Puhdastila"
* #366 "Olosuhdehuone"
* #371 "Ryhmätila"
* #441 "Leikkaussali"
* #4411 "Synnytyssali"
* #442 "Potilashuone"
* #4421 "Eristyshuone"
* #4422 "Tehohoitotila"
* #443 "Kappeli tai jäähyväishuone"
* #444 "Toimenpidehuone"
* #4441 "Vastaanottohuone"
* #44411 "Vastaanottohuone, kevyt"
* #44412 "Vastaanottohuone, erikoisvarustus"
* #4443 "Kuvantamishuone"
* #4445 "Kuvantamishuone, erikoisvarustus"
* #4451 "Valvonta- tai tarkkailutila"
* #4454 "Heräämö"
* #446 "Vainajien säilytystila"
* #447 "Obduktio- tai dissektiotila"
* #448 "Välinehuoltotila"
* #4615 "Kirjasto"
* #471 "Liikuntasali"
* #472 "Kuntosali"
* #4911 "Pelastustoimen laitehuoltotila"
* #521 "Varastotila"
* #5292 "Varastotila, kylmä"
* #5293 "Varastotila, erikoisvarustus"
* #531 "Arkistotila"
* #552 "Auto- tai kalustohalli, lämmin"
* #555 "Pesuhalli"
* #63 "Ruokasali"
* #642 "Keittiö"
* #645 "Jakelukeittiö tai palvelukeittiö"
* #651 "Kylmiö"
* #652 "Pakastehuone"
* #71 "Pukutila"
* #72 "Pesutila"
* #73 "WC-tila"
* #74 "Sauna"
* #751 "Taukotila"
* #752 "Oleskelutila"
* #753 "Valmiushuone"
* #81 "Väestönsuojatila"
* #83 "Sisäänkäyntitila"
* #832 "Aula tai odotustila"
* #86 "Siivous- tai huoltotila"
* #865 "Vaate- tai tekstiilihuoltotila"
* #866 "Teknisen huollon tila"
* #87 "Jätehuoltotila"
* #91 "Käytävä (jakava liikenne)"
* #911 "Sulkutila"
* #912 "Logistiikka- tai terminaalitila"
* #921 "Porrashuone (osastoiva liikenne)"
* #94 "Tekninen tila"
* #941 "Tekninen tila, erikoisvarustus"
* #942 "Tekninen aputila"
* #991 "Raakatila"
* #9911 "Hissi"