name: Build and Deploy FHIR IG

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js (for SUSHI)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install SUSHI
      run: npm install -g fsh-sushi

    - name: Set up Java (for IG Publisher)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download IG Publisher
      run: |
        mkdir -p input-cache
        curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o input-cache/publisher.jar

    - name: Run SUSHI
      run: sushi .

    - name: Build Implementation Guide
      run: java -jar input-cache/publisher.jar -ig .

    - name: Create .nojekyll file
      run: touch output/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
